[package]
name = "stellar-event-assertion"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

# This crate is only used for testing, and not compatible with `wasm32` targets.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.soroban-sdk]
workspace = true
features = ["testutils"]

[dependencies]
stellar-non-fungible = { workspace = true }
